### ISSUE TITLE
java.lang.IndexOutOfBoundsException while running in Spark application

### ISSUE THREAD

**Issue by ahuret** [bkiers/atlas#3]
Hi ! I'm a new user of this library.
When trying to run this code using Spark (+ Fat Jar)

```scala import atlas.Atlas

object main extends App {
        val city = new Atlas().find(48.0000, 2.000);
        println(city)
}
```

I had this error:

```Exception in thread "main" java.lang.ExceptionInInitializerError
	at main$.delayedEndpoint$main$1(main.scala:10)
	at main$delayedInit$body.apply(main.scala:9)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at main$.main(main.scala:9)
	at main.main(main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index: 10, Size: 0
	at atlas.Utils.deserialize(Utils.java:67)
	at atlas.Atlas.<clinit>(Atlas.java:12)
	... 23 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 10, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.esotericsoftware.kryo.util.MapReferenceResolver.getReadObject(MapReferenceResolver.java:60)
	at com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:857)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:707)
	at atlas.Utils.deserialize(Utils.java:63)
	... 24 more
```

It works well using sbt run, but not running it inside Spark application (itself using sbt assembly to generate a Fat Jar)..

Wondering what's wrong here, looks related to kryo serializer.
I'd be glad if you can help me !

Thanks,

Antoine

**Comment by jbguerraz** [comment]
@bkiers Is there any way to help you on that one ? Thank you a lot!

**Comment by bkiers** [comment]
> @bkiers Is there any way to help you on that one ? Thank you a lot!

Not without an [SSCCE](http://sscce.org) for me to reproduce it. Google finds quite some hits on the keywords "kryo IndexOutOfBoundsException readObject": https://www.google.com/search?client=firefox-b-d&q=kryo+IndexOutOfBoundsException+readObject

So you could try to update the Kryo dependency to see if that helps.

**Comment by bkiers** [comment]
I will close this. Feel free to re-open if a SSCCE can be provided for me to reproduce the issue.

**Comment by jbguerraz** [comment]
Thank you @bkiers !
We'll let you know when we'll give it another try (in few days or weeks max)

**Comment by jbguerraz** [comment]
Hello @bkiers 
FTR the issue is Spark using Kryo 4.0.2 and Atlas using Kryo 5.0.1. When asking gently Atlas to use Kryo 4.0.2 as well things works like a charm!

**Comment by bkiers** [comment]
@jbguerraz good to hear that, and thank you for the follow up!
